### ISSUE TITLE
eml does not install package.xml

### ISSUE THREAD

**Issue by cottsay** [ros-gbp/eml-release#1]
`eml` does not currently install its `package.xml`. This does not allow rosdep to detect if the package is installed or not (and if dependencies are met).

Adding `package.xml` to https://github.com/ros-gbp/eml-release/blob/release/hydro/eml/CMakeLists.txt#L5 will fix the problem:

``` cmake
install( FILES EMLConfig.cmake package.xml DESTINATION share/eml )
```

It would be great to see an additional bloom patch for this and a release bump.

Thanks!

**Comment by k-okada** [comment]
I think this is already fixed
