### ISSUE TITLE
indigo release

### ISSUE THREAD

**Issue by shadowmanos** [ros-gbp/eml-release#2]
We have packages that depend on eml but not on other pr2 software.
It would be great if eml was released for ROS indigo.

**Comment by wjwwood** [comment]
@stonier In case you are not watching.

**Comment by stonier** [comment]
I think the person you wanted to ping is @ahendrix.

**Comment by wjwwood** [comment]
Oops, sorry I mistook this for `ecl`, my bad.

**Comment by shadowmanos** [comment]
Thanks guys. Already pinged @ahendrix

**Comment by trainman419** [comment]
Ping @ibaranov-cp and @TheDash , since they're now responsible for the PR2 software.

Note that this is a third-party library; there is no source repository on github.

**Comment by UltronDestroyer** [comment]
This may be of interest: https://github.com/shadow-robot/ros_ethercat

**Comment by trainman419** [comment]
@TheDash yes; they released their own version of eml because you failed to release eml in a timely manner.

**Comment by UltronDestroyer** [comment]
@trainman419 Can I have access to this repo?

**Comment by trainman419** [comment]
@TheDash added.
