### ISSUE TITLE
Lunar & Melodic release

### ISSUE THREAD

**Issue by k-okada** [ros-gbp/eml-release#4]
@davefeilseifer are you interested in releasing this in to lunar and melodic? If you are busy, I can release this repository as a part of “ROS Orphaned Package Maintainers” initiatives

**Comment by davefeilseifer** [comment]
I can release this for lunar and melodic. I'll get to it after the IROS
deadline. Long-term, it is probably worth it to move to the ros_ethercat
package that doesn't rely on pr2_ethercat and the eml package, but there
are significant differences between the APIs and I need some time to figure
that out.

**Comment by davefeilseifer** [comment]
I have released for lunar and melodic, waiting for merge/sync
